
@baseUrl = http://raspberrypi:3000

###
POST {{baseUrl}}/on

###

POST {{baseUrl}}/off

###

GET {{baseUrl}}/status

###

POST {{baseUrl}}/raw HTTP/1.1
content-type: application/json

{
    "transaction":"FF:44:40"
}